name: Deploy to Hugging Face Spaces

on:
  push:
    branches:
      - main  # Déclencher le workflow lors d'un push sur la branche 'main'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2  # Vérifie le code dans le dépôt

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'  # Tu peux choisir la version de Python selon tes besoins

    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install gradio  # Installe les dépendances nécessaires (ajoute d'autres dépendances si nécessaire)

    - name: Push to Hugging Face
      run: |
        git remote add hf https://huggingface.co/spaces//Gauthier76/test1  # Configure Hugging Face comme remote
        git config --global user.name "GitHub Actions"  # Configurer un nom pour les commits
        git config --global user.email "actions@github.com"  # Configurer un email pour les commits
        git add .  # Ajouter les fichiers modifiés
        git commit -m "Deploy updated code to Hugging Face"  # Commit des changements
        git push hf main  # Push vers Hugging Face
      env:
        HF_TOKEN: ${{ secrets.HUGGINGFACE_TOKEN }}  # Utilisation de ton token Hugging Face stocké dans les secrets
