# Configuration de base de Jekyll
title: Mon Site Jekyll
description: Un site statique généré avec Jekyll.
author: Ton Nom

# Thème utilisé
theme: jekyll-theme-primer

# URL du site (facultatif si tu as une URL spécifique)
url: "https://ton-site.github.io"
baseurl: ""

# Paramètres pour la génération du site
markdown: kramdown
highlighter: rouge

# Permet de définir les fichiers ou dossiers à inclure/exclure
include:
  - "_pages"
  - "_posts"
exclude:
  - "Gemfile"
  - "Gemfile.lock"
  - "_config.yml"

# Paramètres spécifiques au thème Jekyll Primer
jekyll_defaults:
  style: "flat"

# Configuration des permaliens pour les articles de blog (si tu utilises des posts)
permalink: pretty
paginate: 5

